language:
    - 'php'
php:
    - '5.6'
before_script:
    - 'composer install'
script:
    - 'php test.php'
    - './vendor/bin/phpunit application/tests --colors'
email:
    on_success: never # default: change
    on_failure: never # default: always
