language: php
php:
    - '5.6'
services:
    - mysql
before_script:
    - ''
    - 'sudo apt-get -y install php5 libapache2-mod-php5'
    - 'sudo /etc/init.d/apache2 restart'
    - 'cd /var/www/'
    - 'sudo mkdir html'
    - 'ls'
    - 'cd html'
    - 'sudo git clone https://github.com/jhonvegamas/phpunit_codeigniter.git'
    - 'sudo chmod 777 -rwx phpunit_codeigniter'
    - 'cd phpunit_codeigniter'
    - 'composer install'
    - 'cd ..'
    - 'ls'
    - 'sudo chmod 777 -R phpunit_codeigniter'
    - 'cd phpunit_codeigniter'

script:
    - 'php createdb.php'
    - './vendor/bin/phpunit application/tests --colors'
email:
    on_success: never # default: change
    on_failure: never # default: always
