language: php
php:
    - '5.6'
services:
    - mysql
before_script:
    - 'git clone https://github.com/jhonvegamas/phpunit_codeigniter.git'
    - 'cd phpunit_codeigniter'
    - 'sudo apt-get -y install php5 libapache2-mod-php5'
    - 'sudo /etc/init.d/apache2 restart'
    - 'cd ..'
    - 'sudo mv phpunit_codeigniter /var/www/html'
    - 'cd /var/www/html'
    - 'rm index.html'
    - 'ls'

script:
    - 'php createdb.php'
    - './vendor/bin/phpunit application/tests --colors'
email:
    on_success: never # default: change
    on_failure: never # default: always
