language: php

php:
    - '5.6'
services:
    - mysql
before_script:
    - 'sudo php -S localhost:80'
    - 'git clone https://github.com/jhonvegamas/phpunit_codeigniter.git'
    - 'cd phpunit_codeigniter'
    - 'composer install'
script:
    - 'php createdb.php'
    - './vendor/bin/phpunit application/tests --colors'
