language: php

php:
    - '5.6'
services:
    - mysql
before_script:
    - 'sudo apt-get install apache2 libapache2-mod-fastcgi'
    - 'sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default'
    - 'sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default'
    - 'sudo service apache2 restart'
    - 'git clone https://github.com/jhonvegamas/phpunit_codeigniter.git'
    - 'cd phpunit_codeigniter'
    - 'composer install'
script:
    - 'php createdb.php'
    - './vendor/bin/phpunit application/tests'
